name: Format Code

on:
  push:
    paths:
      - "src/**.js"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "16.x"
      - run: npm install npm -g
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        run: npm ci
      - name: Run format
        run: npm run format
      - name: Check code style
        run: npm run format:check
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "style: 🎨 format code"
